platform :ios, '6.1'
pod 'HexColors', '~> 2.2'
pod 'UIColor+Additions', '~> 1.0'
pod 'CocoaLumberjack', '~> 1.8'
pod 'FlurrySDK', '~> 4.3'
pod 'iRate', '~> 1.9'
pod 'Facebook-iOS-SDK', '~> 3.13'
pod 'BlocksKit', '~> 2.2'
pod 'EAIntroView', '~> 2.3'
pod 'UIImage-Helpers', '~> 0.0'
pod 'GameCenterManager', '~> 5.3'
pod 'KVOController', '~> 1.0'
pod 'UIView+AutoLayout', '~> 1.3'
