platform :ios, '7.0'
pod 'HexColors', '~> 2.2'
pod 'UIColor+Additions', '~> 1.0'
pod 'CocoaLumberjack', '~> 1.8'
pod 'iRate', '~> 1.9'
pod 'Facebook-iOS-SDK', '~> 3.13'
pod 'BlocksKit', '~> 2.2'
pod 'EAIntroView', '~> 2.3'
pod 'UIImage-Helpers', '~> 0.0'
pod 'KVOController', '~> 1.0'
pod 'UIView+AutoLayout', '~> 1.3'
pod 'Mixpanel', '~> 2.3'
pod 'SVProgressHUD', '~> 1.0'
pod 'Reachability', '~> 3.1'
